/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Artigo;
import Classes.Livros;
import Classes.Manga;
import Classes.MidiasEletronicas;
import Classes.NormasTecnicas;
import Classes.Periodicos;
import Classes.Quadrinhos;
import Controller.ControllerObra;
import Modelo.Obra;
import javax.swing.JOptionPane;

/**Classe para a criação da tela que Edita uma Obra.
 * @author Kyllder
 * @author Thiago
 * @author Pedro
 * @version 1.0
 */
public class TelaEditarO extends javax.swing.JDialog {
    /**Um objeto do Controller de Obra.
     *@see ControllerObra*/
    private ControllerObra co = new ControllerObra();
    /**Um objeto de Obra.
     *@see Obra*/
    private Obra o;
    /**
     * Construtor da classe, onde são inicializados todos os componentes da tela
     * e onde são habilitados ou desabilitados os componentes de acordo com o tipo de obra
     * @param parent O JFrame pai da tela
     * @param modal se quer continuar com o modelo
     * @param o a Obra
     */
    public TelaEditarO(java.awt.Frame parent, boolean modal,Obra o) {
        super(parent, modal);
        initComponents();
        txtNome.setText(o.getNome());
        txtAssunto.setText(o.getAssunto());
        txtAutor.setText(o.getAutor());
        txtEditora.setText(o.getEditora());
        txtGenero.setText(o.getGenero());
        txtNumero.setText(o.getNumero());
        Tipo.setSelectedItem(o.getTipo());
        txtCopias.setText(""+o.getCopias());
        Selecionado(o.getTipo());
        this.o=o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtGenero = new javax.swing.JTextField();
        LTipo = new javax.swing.JLabel();
        LNome = new javax.swing.JLabel();
        Tipo = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        LNumero = new javax.swing.JLabel();
        LAssunto = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtAssunto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        RLivro1 = new javax.swing.JRadioButton();
        RPeriodicos1 = new javax.swing.JRadioButton();
        RNormas1 = new javax.swing.JRadioButton();
        RQuadrinhos1 = new javax.swing.JRadioButton();
        RArtigo1 = new javax.swing.JRadioButton();
        RMidias1 = new javax.swing.JRadioButton();
        RManga1 = new javax.swing.JRadioButton();
        LAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        LEditora = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        LGenero = new javax.swing.JLabel();
        Editar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        LCopias = new javax.swing.JLabel();
        txtCopias = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTipo.setText("Tipo de Mídia:");

        LNome.setText("Nome:");

        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CD", "DVD" }));

        LNumero.setText("Numero:");

        LAssunto.setText("Assunto:");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        buttonGroup1.add(RLivro1);
        RLivro1.setText("Livro");
        RLivro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RLivro1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RPeriodicos1);
        RPeriodicos1.setText("Periódicos");
        RPeriodicos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPeriodicos1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RNormas1);
        RNormas1.setText("Normas Técnicas");
        RNormas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RNormas1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RQuadrinhos1);
        RQuadrinhos1.setText("Quadrinhos");
        RQuadrinhos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RQuadrinhos1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RArtigo1);
        RArtigo1.setText("Artigos");
        RArtigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RArtigo1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RMidias1);
        RMidias1.setText("Mídias Eletrônicas");
        RMidias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RMidias1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RManga1);
        RManga1.setText("Mangá");
        RManga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RManga1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RPeriodicos1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RNormas1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RQuadrinhos1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RManga1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RArtigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMidias1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RLivro1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(RLivro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RPeriodicos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RNormas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RQuadrinhos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RManga1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RArtigo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RMidias1))
        );

        LAutor.setText("Autor:");

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        LEditora.setText("Editora:");

        LGenero.setText("Gênero:");

        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book_edit.png"))); // NOI18N
        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        LCopias.setText("Copias:");

        txtCopias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LNome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(LAssunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(LEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LCopias)
                                .addGap(18, 18, 18)
                                .addComponent(txtCopias, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(LNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LTipo)
                                        .addGap(18, 18, 18)
                                        .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(434, 434, 434))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LAssunto)
                            .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LAutor)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LEditora)
                            .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LGenero)
                            .addComponent(LNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LCopias)
                            .addComponent(txtCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LTipo)
                            .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     *  Método Não faz nada foi, gerado sem querer
     * 
     */
    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed
    /**
     *  Chama o método selecionado como tipo Livro
     * @see Selecionado()
     */
    private void RLivro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RLivro1ActionPerformed
        Selecionado("Livro");
    }//GEN-LAST:event_RLivro1ActionPerformed
/**
     *  Chama o método selecionado como tipo Periodicos
     * @see Selecionado()
     */
    private void RPeriodicos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPeriodicos1ActionPerformed
        Selecionado("Periodicos");
    }//GEN-LAST:event_RPeriodicos1ActionPerformed
/**
     *  Chama o método selecionado como tipo NormasTecnicas
     * @see Selecionado()
     */
    private void RNormas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RNormas1ActionPerformed
        Selecionado("NormasTecnicas");
    }//GEN-LAST:event_RNormas1ActionPerformed
/**
     *  Chama o método selecionado como tipo Quadrinhos
     * @see Selecionado()
     */
    private void RQuadrinhos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RQuadrinhos1ActionPerformed
        Selecionado("Quadrinhos");
    }//GEN-LAST:event_RQuadrinhos1ActionPerformed
/**
     *  Chama o método selecionado como tipo Artigo
     * @see Selecionado()
     */
    private void RArtigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RArtigo1ActionPerformed
        Selecionado("Artigo");
    }//GEN-LAST:event_RArtigo1ActionPerformed
/**
     *  Chama o método selecionado como tipo DVD
     * @see Selecionado()
     */
    private void RMidias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RMidias1ActionPerformed
        Selecionado("DVD");
    }//GEN-LAST:event_RMidias1ActionPerformed
/**
     *  Chama o método selecionado como tipo Manga
     * @see Selecionado()
     */
    private void RManga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RManga1ActionPerformed
        Selecionado("Manga");
    }//GEN-LAST:event_RManga1ActionPerformed
/**
     *  Método Não faz nada foi, gerado sem querer
     * 
     */
    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed
/**
     * Método que cancela a operação e fecha a fecha a tela 
     * @param evt ActionEvent, Ação do botão sendo clicado
     */
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed
/**
     * Método que edita uma Obra.
     * @param evt ActionEvent, Ação do botão sendo clicado
     */
    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
     
        Obra aux=null;
        boolean teste = false;
        if (RLivro1.isSelected()) {
            aux = new Livros(txtNome.getText(), txtAssunto.getText(), txtAutor.getText(), txtEditora.getText(), txtGenero.getText(),Integer.parseInt(txtCopias.getText()),o.getCod());
            teste = true;
        }else if (RPeriodicos1.isSelected()) {
            aux = new Periodicos(txtNome.getText(),txtEditora.getText(),txtAssunto.getText(),txtNumero.getText(),Integer.parseInt(txtCopias.getText()),o.getCod());
            teste = true;
        }else if (RNormas1.isSelected()) {
            aux = new NormasTecnicas(txtNome.getText(), txtAssunto.getText(), txtNumero.getText(),Integer.parseInt(txtCopias.getText()), o.getCod());
            teste = true;
        }else if (RQuadrinhos1.isSelected()) {
            aux = new Quadrinhos(txtNome.getText(), txtAssunto.getText(), txtEditora.getText(), txtAutor.getText(),Integer.parseInt(txtCopias.getText()), o.getCod());
            teste = true;
        }else if (RManga1.isSelected()) {
            aux = new Manga(txtGenero.getText(), txtNome.getText(), txtAssunto.getText(), txtEditora.getText(), txtAutor.getText(),Integer.parseInt(txtCopias.getText()), o.getCod());
            teste = true;
        }else if (RArtigo1.isSelected()) {
            aux = new Artigo(txtNome.getText(), txtAssunto.getText(), txtAutor.getText(),Integer.parseInt(txtCopias.getText()), o.getCod());
            teste = true;
        }else if (RMidias1.isSelected()) {
            aux = new MidiasEletronicas(txtNome.getText(), txtAutor.getText(), txtAssunto.getText(), (String)Tipo.getSelectedItem(),Integer.parseInt(txtCopias.getText()), o.getCod());
            teste = true;
        }else{
            JOptionPane.showMessageDialog(null,"Selecione uma categoria ","Aviso",JOptionPane.ERROR_MESSAGE);
        }
        if (teste) {
            co.Editar(aux);
            this.dispose();
        }
        
    }//GEN-LAST:event_EditarActionPerformed
    /**
     * Método que habilita ou desabilita os componentes de acordo com o tipo.
     * @param tipo String, tipo de Obra
     */
    private void Selecionado(String tipo){
        if (tipo.equals("Livro")) {
            txtNome.setEnabled(true);
            LNome.setEnabled(true);
            txtAssunto.setEnabled(true);
            LAssunto.setEnabled(true);
            txtAutor.setEnabled(true);
            LAutor.setEnabled(true);
            txtEditora.setEnabled(true);
            LEditora.setEnabled(true);
            txtGenero.setEnabled(true);
            LGenero.setEnabled(true);
            txtNumero.setEnabled(false);
            txtNumero.setText("");
            LNumero.setEnabled(false);
            Tipo.setEnabled(false);
            LTipo.setEnabled(false);
            RLivro1.setSelected(true);
        }else if (tipo.equals("Periodicos")) {
            txtNome.setEnabled(true);
            LNome.setEnabled(true);
            txtAssunto.setEnabled(true);
            LAssunto.setEnabled(true);
            txtAutor.setEnabled(false);
            txtAutor.setText("");
            LAutor.setEnabled(false);
            txtEditora.setEnabled(true);
            txtEditora.setText("");
            LEditora.setEnabled(true);
            txtGenero.setEnabled(false);
            txtGenero.setText("");
            LGenero.setEnabled(false);
            txtNumero.setEnabled(true);
            LNumero.setEnabled(true);
            Tipo.setEnabled(false);
            LTipo.setEnabled(false);
            RPeriodicos1.setSelected(true);
        }else if (tipo.equals("NormasTecnicas")) {
            txtNome.setEnabled(true);
            LNome.setEnabled(true);
            txtAssunto.setEnabled(true);
            LAssunto.setEnabled(true);
            txtAutor.setEnabled(false);
            txtAutor.setText("");
            LAutor.setEnabled(false);
            txtEditora.setEnabled(false);
            txtEditora.setText("");
            LEditora.setEnabled(false);
            txtGenero.setEnabled(false);
            txtGenero.setText("");
            LGenero.setEnabled(false);
            txtNumero.setEnabled(true);
            LNumero.setEnabled(true);
            Tipo.setEnabled(false);
            LTipo.setEnabled(false);
            RNormas1.setSelected(true);
        }else if (tipo.equals("Quadrinhos")) {
            txtNome.setEnabled(true);
            LNome.setEnabled(true);
            txtAssunto.setEnabled(true);
            LAssunto.setEnabled(true);
            txtAutor.setEnabled(true);
            LAutor.setEnabled(true);
            txtEditora.setEnabled(true);
            LEditora.setEnabled(true);
            txtGenero.setEnabled(false);
            txtGenero.setText("");
            LGenero.setEnabled(false);
            txtNumero.setEnabled(false);
            txtNumero.setText("");
            LNumero.setEnabled(false);
            Tipo.setEnabled(false);
            LTipo.setEnabled(false);
            RQuadrinhos1.setSelected(true);
        }else if (tipo.equals("Manga")) {
            txtNome.setEnabled(true);
            LNome.setEnabled(true);
            txtAssunto.setEnabled(true);
            LAssunto.setEnabled(true);
            txtAutor.setEnabled(true);
            LAutor.setEnabled(true);
            txtEditora.setEnabled(true);
            LEditora.setEnabled(true);
            txtGenero.setEnabled(true);
            LGenero.setEnabled(true);
            txtNumero.setEnabled(false);
            txtNumero.setText("");
            LNumero.setEnabled(false);
            Tipo.setEnabled(false);
            LTipo.setEnabled(false);
            RManga1.setSelected(true);
        }else if (tipo.equals("Artigo")) {
            txtNome.setEnabled(true);
            LNome.setEnabled(true);        
            txtAssunto.setEnabled(true);
            LAssunto.setEnabled(true);
            txtAutor.setEnabled(true);
            LAutor.setEnabled(true);
            txtEditora.setEnabled(false);
            txtEditora.setText("");
            LEditora.setEnabled(false);
            txtGenero.setEnabled(false);
            txtGenero.setText("");
            LGenero.setEnabled(false);
            txtNumero.setEnabled(false);
            txtNumero.setText("");
            LNumero.setEnabled(false);
            Tipo.setEnabled(false);
            LTipo.setEnabled(false);
            RArtigo1.setSelected(true);
        }else if (tipo.equals("CD")|| o.getTipo().equals("DVD")) {
            txtNome.setEnabled(true);
            LNome.setEnabled(true);
            txtAssunto.setEnabled(true);
            LAssunto.setEnabled(true);
            txtAutor.setEnabled(true);
            LAutor.setEnabled(true);
            txtEditora.setEnabled(false);
            txtEditora.setText("");
            LEditora.setEnabled(false);    
            txtGenero.setEnabled(false);
            txtGenero.setText("");
            LGenero.setEnabled(false);
            txtNumero.setEnabled(false);
            txtNumero.setText("");
            LNumero.setEnabled(false);
            Tipo.setEnabled(true);
            LTipo.setEnabled(true);
            RMidias1.setSelected(true);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Editar;
    private javax.swing.JLabel LAssunto;
    private javax.swing.JLabel LAutor;
    private javax.swing.JLabel LCopias;
    private javax.swing.JLabel LEditora;
    private javax.swing.JLabel LGenero;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LNumero;
    private javax.swing.JLabel LTipo;
    private javax.swing.JRadioButton RArtigo1;
    private javax.swing.JRadioButton RLivro1;
    private javax.swing.JRadioButton RManga1;
    private javax.swing.JRadioButton RMidias1;
    private javax.swing.JRadioButton RNormas1;
    private javax.swing.JRadioButton RPeriodicos1;
    private javax.swing.JRadioButton RQuadrinhos1;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JFormattedTextField txtCopias;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
