/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Emprestimo;
import Controller.ControllerEmprestimo;
import Controller.ControllerObra;
import Controller.ControllerUsuario;
import Exception.DataPrevistaInvalida;
import Modelo.Obra;
import Modelo.Usuarios;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Classe para a criação da tela que adiciona um Emprestimo.
 * @author Kyllder
 * @author Thiago
 * @author Pedro
 * @version 1.0
 */
public class TelaAddEmprestimo extends javax.swing.JFrame {
   /**Um objeto do Controller de Emprestimos.
     *@see ControllerEmprestimo*/
    private ControllerEmprestimo ce =new ControllerEmprestimo();
    /**Um ArrayList que armazenas todas as obras*/
    private ArrayList<Obra > arrayO= new ArrayList();
    /**Um objeto do default table model, relacionado a tabela de obras.
     *@see DefaultTableModel*/
    private DefaultTableModel dtmO;
    /**Um objeto do Controller de Obras.
     *@see ControllerObra*/
    private ControllerObra co =new ControllerObra();
    /**Um objeto do Controller de Usuario.
     *@see ControllerUsuario*/
    private ControllerUsuario cobre =new ControllerUsuario();
    /**Um ArrayList que armazenas todos os usuarios*/
    private ArrayList<Usuarios> arrayU= new ArrayList();
     /**Um objeto do default table model, relacionado a tabela de usuarios.
     *@see DefaultTableModel*/
    private DefaultTableModel dtmU;
     /**Uma String que armazena o nome do administrador*/
    private String Admin;
    /**
     * Construtor da classe, onde são inicializados todos os componentes da tela
     * e onde são adicionados os dados da tabela 
     * @param Admin o nome do Administrador que está logado
     */
    public TelaAddEmprestimo(String Admin) { 
        initComponents();
        this.Admin=Admin;
        
        dtmO = (DefaultTableModel)TabelaObra.getModel();    
        arrayO=co.Listar();
        if (!arrayO.isEmpty()) {     
            for (Obra aux: arrayO) {
                String disponivel="Não";
                if (ce.CopiaDisponivel(aux.getNome(),aux.getCopias())) {
                    disponivel="Sim";
                }
            String a[]={aux.getNome(),aux.getAutor(),aux.getAssunto(),aux.getEditora(),aux.getGenero(),aux.getNumero(),aux.getTipo(),disponivel};
            dtmO.addRow(a);
        }
        }
        
        dtmU = (DefaultTableModel)TabelaUsuario.getModel();
        arrayU=cobre.Listar();
        if (!arrayU.isEmpty()) {           
            for (Usuarios aux: arrayU) {
            String a[]={aux.getNome(),aux.getCPF(),aux.getRG(),aux.getTelefone(),aux.getEndereco(),aux.getTipo()};
            dtmU.addRow(a);
        }
        }
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaObra = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaUsuario = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarObra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Adicionar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TabelaObra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Autor", "Assunto", "Editora", "Gênero", "Numero", "Tipo", "Disponivel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaObra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TabelaObraMouseMoved(evt);
            }
        });
        TabelaObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaObraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaObra);

        TabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "RG", "Telefone", "Endereço", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TabelaUsuarioMouseMoved(evt);
            }
        });
        TabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaUsuario);

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier.png"))); // NOI18N
        jLabel1.setText("Procurar");

        txtBuscarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarObraActionPerformed(evt);
            }
        });
        txtBuscarObra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarObraKeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier.png"))); // NOI18N
        jLabel3.setText("Procurar");

        Adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book_next.png"))); // NOI18N
        Adicionar.setText("Adicionar");
        Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarActionPerformed(evt);
            }
        });

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     *  Método Não faz nada foi, gerado sem querer
     * 
     */
    private void TabelaObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaObraMouseClicked

    }//GEN-LAST:event_TabelaObraMouseClicked
/**
     *  Método Não faz nada foi, gerado sem querer
     * 
     */
    private void TabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaUsuarioMouseClicked

    }//GEN-LAST:event_TabelaUsuarioMouseClicked
/**
     *  Método Não faz nada foi, gerado sem querer
     * 
     */
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
       
    }//GEN-LAST:event_txtBuscarActionPerformed
    /**
     * Método que atualiza a tabela de usuarios a cada vez que o campo de texto é alterado
     * @param evt KeyEvent, Ação do Campo de texto ao ser digitado ou apagado algo
     */
    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
       dtmU =  (DefaultTableModel)TabelaUsuario.getModel();
        if (!txtBuscar.getText().equals("")) {
            dtmU.setNumRows(0);
            ArrayList<Usuarios> array1=cobre.Buscar(txtBuscar.getText());
            for (Usuarios aux : array1) {
                String a[]={aux.getNome(),aux.getCPF(),aux.getRG(),aux.getTelefone(),aux.getEndereco(),aux.getTipo()};
                dtmU.addRow(a);
            }

        }else{
            dtmU.setNumRows(0);
            for (Usuarios aux : arrayU) {
                String a[]={aux.getNome(),aux.getCPF(),aux.getRG(),aux.getTelefone(),aux.getEndereco(),aux.getTipo()};
                dtmU.addRow(a);
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

     /**  Método Não faz nada foi, gerado sem querer
     * 
     */
    private void txtBuscarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarObraActionPerformed
/**
     * Método que atualiza a tabela de Obra a cada vez que o campo de texto é alterado
     * @param evt KeyEvent, Ação do Campo de texto ao ser digitado ou apagado algo
     */
    private void txtBuscarObraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarObraKeyReleased
        
        if (!txtBuscarObra.getText().equals("")) {
            dtmO.setNumRows(0);
            ArrayList<Obra> array1=co.Buscar(txtBuscarObra.getText());
            for (Obra aux : array1) {
                String disponivel="Não";
                if (ce.CopiaDisponivel(aux.getNome(),aux.getCopias())) {
                    disponivel="Sim";
                }
                String a[]={aux.getNome(),aux.getAutor(),aux.getAssunto(),aux.getEditora(),aux.getGenero(),aux.getNumero(),aux.getTipo(),disponivel};
                dtmO.addRow(a);
            }

        }else{
            dtmO.setNumRows(0);
            for (Obra aux : arrayO) {
                String disponivel="Não";
                if (ce.CopiaDisponivel(aux.getNome(),aux.getCopias())) {
                    disponivel="Sim";
                }
                String a[]={aux.getNome(),aux.getAutor(),aux.getAssunto(),aux.getEditora(),aux.getGenero(),aux.getNumero(),aux.getTipo(),disponivel};
                dtmO.addRow(a);
            }
        }
    }//GEN-LAST:event_txtBuscarObraKeyReleased
 /**
     * Método que cancela a operação e fecha a fecha a tela 
     * @param evt ActionEvent, Ação do botão sendo clicado
     */

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed
/**
     * Método que cria um Emprestimo.
     * @param evt ActionEvent, Ação do botão sendo clicado
     */
    private void AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarActionPerformed
        if (TabelaObra.getSelectedRow()>=0 && TabelaUsuario.getSelectedRow()>=0) {
            String nome = (String) TabelaObra.getValueAt(TabelaObra.getSelectedRow(),0);
            String assunto = (String) TabelaObra.getValueAt(TabelaObra.getSelectedRow(),2);
            String tipo = (String) TabelaObra.getValueAt(TabelaObra.getSelectedRow(),6);
            int copias=0;
            for (Obra o : arrayO) {
                if(o.getNome().equals(nome) && o.getAssunto().equals(assunto) && o.getTipo().equals(tipo)){
                    copias=o.getCopias();
                    break;
                }
            }
            
            if (ce.CopiaDisponivel(nome, copias)) {
                Calendar dtPrevista = Calendar.getInstance();
                String cpf = (String) TabelaUsuario.getValueAt(TabelaUsuario.getSelectedRow(),1);
                for (Usuarios aux : arrayU) {
                if(aux.getCPF().equals(cpf)){
                    if (aux.getDivida()>0) {
                       ce.TelaDivida(this,true,aux.getDivida(), aux);
                    }
                    break;
                }
            }
                
                arrayU=cobre.Listar();
                try {
            for (Usuarios aux : arrayU) {
                if(aux.getCPF().equals(cpf)){
                    if (aux.getDivida()==0) {
                    	if(Calendar.getInstance().compareTo(dtPrevista)>0){
                    		throw new DataPrevistaInvalida("A data atual n�o pode ser maior que a data prevista!");
                    	}
                        dtPrevista.add(Calendar.DATE,aux.getDias());
                        Emprestimo e = new Emprestimo(aux.getNome(), Admin, (String)TabelaObra.getValueAt(TabelaObra.getSelectedRow(),0), dtPrevista, null, Calendar.getInstance());
                        ce.Adcionar(e);
                        dispose();
                    }
                }
            }
                } catch (DataPrevistaInvalida dpi) {
					System.out.println(dpi.getMessage());			}
            }else{
                JOptionPane.showMessageDialog(null,"Cópias indisponíveis","Erro",JOptionPane.WARNING_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Selecione ums Obra e um Usuário","Aviso",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AdicionarActionPerformed
    /**
     * Método que cria o comentario dos valores da tabela de obra
     * @param evt MouseEvent, ação de mover o mouse pela tabela
     */
    private void TabelaObraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaObraMouseMoved
        Point p = evt.getPoint(); 
        int row = TabelaObra.rowAtPoint(p);
        int column = TabelaObra.columnAtPoint(p);
        TabelaObra.setToolTipText(String.valueOf(dtmO.getValueAt(row,column)));
    }//GEN-LAST:event_TabelaObraMouseMoved
/**
     * Método que cria o comentario dos valores da tabela de usuario
     * @param evt MouseEvent, ação de mover o mouse pela tabela
     */
    private void TabelaUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaUsuarioMouseMoved
        Point p = evt.getPoint(); 
        int row = TabelaUsuario.rowAtPoint(p);
        int column = TabelaUsuario.columnAtPoint(p);
        TabelaUsuario.setToolTipText(String.valueOf(dtmU.getValueAt(row,column)));
    }//GEN-LAST:event_TabelaUsuarioMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTable TabelaObra;
    private javax.swing.JTable TabelaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarObra;
    // End of variables declaration//GEN-END:variables
}
